schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "MyEnvironmentInputs"
  types:
    MyEnvironmentInputs:
      title: Environment test inputs for Strings
      description: Properties that exercise the various options for specifying string types in OpenAPI
      type: object
      required:
        - simple_string

      properties:
        simple_string:
          title: A simple string parameter
          description: String parameter with title, description, a default value, length validation (min = 2, max = 10) and an example - Supported ✓
          type: string
          default: task
          example: my example string
          maxLength: 10
          minLength: 2

        simple_string_not_required:
          title: An optional simple string parameter
          description: Optional string parameter - Supported ✓
          type: string

        enum_string:
          title: A simple string parameter using Enums
          description: Simple string input using Enums (Dropdown) - Supported ✓
          type: string
          enum:
            - String enum 1
            - String enum 2

        string_array:
          title: String Array
          description: String array parameter with title, description, a default value, length validation (min = 1, max = 5) and an example - Supported ✓
          type: array
          maxItems: 5
          minItems: 1
          default:
            - Hello world
          example:
            - hello
            - world
          items:
            type: string

        formatted_string:
          description: String parameter set with format = date, the validation on the console is not supported though the Proton API will return an error if the input is NOT a Date - NOT Supported ✗
          type: string
          format: date
