schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "MyEnvironmentInputType"
  types:

    MyEnvironmentInputType:
      title: Environment test input
      description: Input properties for my environment
      type: object
      required:
        - my_sample_input

      properties:
        my_sample_input:
          type: string
          description: "This is a sample input"
          default: "hello world"

    StringTests:
      title: Tests for strings
      description: Properties that exercise the various options for specifying string types in OpenAPI
      type: object
      required:
        - simple_string

      properties:
        simple_string:
          description: Simple string input (Text input) - Supported ✓
          type: string

        enum_string:
          description: Simple string input using Enums (Dropdown) - Supported ✓
          type: string
          enum:
            - choice1
            - choice2

        formatted_string:
          description: String parameter set with format = date - NOT Supported ✗
          type: string
          format: date

        string_array:
          description: Array of simple strings parameter (Text input) - To be tested!
          type: array
          items:
            type: string

        string_enums_array:
          description: Array of simple strings parameter using enums (Dropdown) - To be tested!
          type: array
          items:
            enum:
              - choice1
              - choice2

        complex_string:
          description: String param with title, description, length validation, examples
            and default value
          title: Complex String 123
          type: string
          default: task
          example: my example string
          maxLength: 50
          minLength: 1

        complex_string_array:
          default:
            - Hello world
          description: String array param with title, description, min/max items validation,
            example, and default value
          example:
            - hello
            - world
          items:
            type: string
          maxItems: 10
          minItems: 1
          title: Complex String Array 345
          type: array
