schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "MyEnvironmentInputType"
  types:
    MyEnvironmentInputType:
      description: "Input properties for my environment"
      type: object
      required:
        - my_sample_input

      properties:
        my_sample_input:
          type: string
          description: "This is a sample input"
          default: "hello world"
