schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "MyEnvironmentInputType"
  types:

    MyEnvironmentInputType:
      title: Environment test input
      description: Input properties for my environment
      type: object
      required:
        - my_sample_input

      properties:
        my_sample_input:
          type: string
          description: "This is a sample input"
          default: "hello world"

    StringTests:
      title: Tests for strings
      description: Properties that exercise the various options for specifying string types in OpenAPI
      type: object
      required:
        - simple_string

      properties:
        simple_string:
          title: A simple string parameter
          description: String parameter with title, description, a default value, length validation (min = 2, max = 10) and an example - Supported ✓
          type: string
          default: task
          example: my example string
          maxLength: 10
          minLength: 2

        enum_string:
          title: A simple string parameter using Enums
          description: Simple string input using Enums (Dropdown) - Supported ✓
          type: string
          enum:
            - String enum 1
            - String enum 2

        string_array:
          title: String Array
          description: String array parameter with title, description, a default value, length validation (min = 1, max = 5) and an example - Supported ✓
          type: array
          maxItems: 5
          minItems: 1
          default:
            - Hello world
          example:
            - hello
            - world
          items:
            type: string

        formatted_string:
          description: String parameter set with format = date - NOT Supported ✗
          type: string
          format: date
