Resources:
  StoreInputValue:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: "open-api-number-tests {{ environment.inputs.simple_number}}"

Outputs:
  MyEnvParameterValue:
    Value: !GetAtt StoreInputValue.Value
