schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "MyEnvironmentInputs"
  types:
    MyEnvironmentInputs:
      title: Environment test inputs for Booleans
      description: Properties that exercise the various options for specifying boolean types in OpenAPI
      type: object
      required:
        - simple_boolean

      properties:
        simple_boolean:
          title: A simple boolean parameter
          description: Boolean parameter with title, description, a default value, and an example - Supported ✓
          type: boolean
          default: true
          example:
            - true
            - false

        enum_boolean:
          title: A simple boolean parameter using Enums
          description: Simple boolean input using Enums (Dropdown) - Supported ✓
          type: boolean
          enum:
            - true
            - false

        boolean_array:
          title: Boolean Array
          description: Boolean array parameter with title, description, a default value, items count validation (min = 1, max = 5) and an example - Supported ✓
          type: array
          maxItems: 5
          minItems: 1
          default:
            - true
          example:
            - true
            - false
          items:
            type: boolean
