schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "MyEnvironmentInputs"
  types:
    MyEnvironmentInputs:
      title: Environment test inputs for Integers
      description: Properties that exercise the various options for specifying string types in OpenAPI
      type: object
      required:
        - simple_integer

      properties:
        simple_integer:
          title: A simple integer parameter
          description: Integer parameter with title, description, a default value, min/max validation (min = 2, max = 10) and an example - Supported ✓
          type: integer
          default: 5
          example: 2
          max: 10
          min: 2

        enum_integer:
          title: A simple integer parameter using Enums
          description: Simple integer input using Enums (Dropdown) - Supported ✓
          type: integer
          enum:
            - 1
            - 2
            - 3

        integer_array:
          title: Integer Array
          description: Integer array parameter with title, description, a default value, length validation (min = 1, max = 5) and an example - Supported ✓
          type: array
          maxItems: 5
          minItems: 1
          default:
            - 1
          example:
            - 1
            - 2
            - 3
          items:
            type: integer

        formatted_Integer:
          description: Integer parameter set with format = int64, the validation on the console is not supported though the Proton API will return an error if the input is NOT a int64 - NOT Supported ✗
          type: string
          format: int64
