schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "MyEnvironmentInputs"
  types:
    MyEnvironmentInputs:
      title: Environment test inputs for Integers
      description: Properties that exercise the various options for specifying integer types in OpenAPI
      type: object
      required:
        - simple_integer

      properties:
        simple_integer:
          title: A simple integer parameter
          description: Integer parameter with title, description, a default value, min/max validation (min = 2, max = 10) and an example - Supported ✓
          type: integer
          default: 5
          example: 2
          maximum: 10
          minimum: 2

        enum_integer:
          title: A simple integer parameter using Enums
          description: Simple integer input using Enums (Dropdown) - Supported ✓
          type: integer
          enum:
            - 1
            - 2
            - 3

        integer_array:
          title: Integer Array
          description: Integer array parameter with title, description, a default value, min/max validation (min = 10, max = 50), length validation (min = 1, max = 5) and an example - Supported ✓
          type: array
          maximum: 50
          minimum: 10
          maxItems: 5
          minItems: 1
          default:
            - 10
          example:
            - 1
            - 2
            - 3
          items:
            type: integer

        integer_array_min_max:
          title: Integer Array
          description: Integer with min/max validation (min = 10, max = 50) - NOT Supported ✗
          type: array
          maximum: 50
          minimum: 10
          items:
            type: integer

        formatted_integer:
          description: Integer parameter set with format = int8, UI will show the proper input but will NOT validate the format. Proton will validate on the backend - NOT Supported ✗
          type: integer
          format: int8
